[install]
# Use the exact versions specified in package.json
exact = true

[install.scopes]
# Configure scope for private packages if needed
"@company" = "https://registry.company.com"

[test]
# Configure test environment
coverage = true